/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ncom;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Adriana
 */
public class EDT extends javax.swing.JFrame {

    /**
     * Creates new form EDT
     */
    public EDT() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/utn.jpeg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabelNcom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numeroIngresado = new javax.swing.JTextField();
        btn_transformar = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelFondoRojo = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNcom.setFont(new java.awt.Font("ISOCPEUR", 1, 30)); // NOI18N
        jLabelNcom.setText("TRANSFORMACIONES");
        getContentPane().add(jLabelNcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Número Complejo : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 132, -1, -1));

        numeroIngresado.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        numeroIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroIngresadoActionPerformed(evt);
            }
        });
        getContentPane().add(numeroIngresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 174, -1));

        btn_transformar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_transformar.setText("TRANSFORMAR");
        btn_transformar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transformarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transformar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        resultado.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 179, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Resultado : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 263, -1, -1));

        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("ISOCPEUR", 1, 44)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("[NCOM]");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jLabelFondoRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoRojo2.png"))); // NOI18N
        jLabelFondoRojo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelFondoRojo.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabelFondoRojoComponentAdded(evt);
            }
        });
        getContentPane().add(jLabelFondoRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_transformarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transformarActionPerformed
        String num = numeroIngresado.getText();
        parser pars = new parser(num);
        String datos = num.substring(1,num.length()-1);
        String complejos[] = datos.split(",");
        double parteReal;
        double parteImaginaria;
        boolean tipo;
        switch (pars.armarNumero()) {
            case 1:
                {
                    //BINOMICA
                    parteReal = Double.parseDouble(complejos[0]);
                    parteImaginaria = Double.parseDouble(complejos[1]);
                    tipo = false;
                    Numero numero = new Numero(parteReal,parteImaginaria,tipo);
                    numero.transformar();
                    resultado.setText("[" + numero.a + "," + numero.b + "]");
                    break;
                }
            case 2:
                {
                    //POLAR
                    parteReal = Double.parseDouble(complejos[0]);
                    parteImaginaria = Double.parseDouble(complejos[1]);
                    tipo = true;
                    Numero numero = new Numero(parteReal,parteImaginaria,tipo);
                    numero.transformar();
                    resultado.setText("(" + numero.a + "," + numero.b + ")");
                    break;
                }
            default:
                JOptionPane.showMessageDialog( null,
                        "Valor ingresado incorrecto",
                        "Atencion",
                        JOptionPane.WARNING_MESSAGE);
                break;
        }
        
    }//GEN-LAST:event_btn_transformarActionPerformed

    private void numeroIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroIngresadoActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void jLabelFondoRojoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabelFondoRojoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondoRojoComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main menu = new Main();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_transformar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFondoRojo;
    private javax.swing.JLabel jLabelNcom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numeroIngresado;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
